# use the simple server factory if you only want to run on a single port
#server:
#  type: simple
#  connector:
#    type: http
#    port: 8080
dbConfig:
  dbName : mogambo
  port : 27017
  host : ec2-52-74-121-28.ap-southeast-1.compute.amazonaws.com

server:
#  softNofileLimit: 1000
#  hardNofileLimit: 1000
  applicationConnectors:
  - type: http
    port: 39112
  adminConnectors:
  - type: http
    port: 39113

logging:
  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  appenders:
      - type: file
        currentLogFilename: dropwizard-activity.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: dropwizard-activity-%d.log
        archivedFileCount: 5
        timeZone: UTC
      - type: console
        threshold: ALL
        timeZone: UTC
        target: stdout